### ISSUE TITLE
User story 1 (List of all answered Questions)

### ISSUE THREAD

**Issue by mariusgolabski** [mariusgolabski/capstone-project#1]
## Value proposition

As a Leader,
I want to see a list of my answered questions,
so that I can have a complete overview of the questions I've addressed.

## Description

![Image](https://github.com/mariusgolabski/capstone-project/assets/137039242/86310b35-ab2a-477e-81c5-5cf07cfbba33)

## Acceptance criteria

- [x] All answered questions are displayed as a list
- [x] Each answered question's category is displayed
- [x] Each answered question's question is displayed
- [x] Each answered question's answer is displayed

## Tasks

- [x] Create a file named interviewQuestionsData.js to hold your simulated data
- [x] Create the component InterviewQuestionsList to render a list.
- [x] Create the component InterviewQuestionCard for displaying an individual interview question.
- [x] Import the interviewQuestionsData array into your InterviewQuestionsList component and map through it to 
   render the individual questions using the InterviewQuestionCard component.
- [x] Each object should include properties such as a id, category, question, and answer.
 

## Size

S
