### ISSUE TITLE
User Story 2 (Filterable Answered Question Categories)

### ISSUE THREAD

**Issue by mariusgolabski** [mariusgolabski/capstone-project#2]
## Value proposition

As a Leader,
I want to filter my answered questions by categories,
so that I can quickly access specific sets of questions based on their topics.

## Description

![Image](https://github.com/mariusgolabski/capstone-project/assets/137039242/88c556b0-1c90-40b2-9586-d5d9a5035cc7)

## Acceptance criteria

- [x] The answered questions section should display a set of buttons representing various categories.
- [x] Upon loading the "answered questions" section, preselect the "All" button as the default.
- [x] Upon clicking a category button, the list of answered questions should dynamically update, displaying only 
        questions from the selected category.
- [x] Visually highlight the currently selected category to provide clarity.

## Tasks

- [x] Create a button component to represent the category, including All.
- [x] Implement the logic to preselect the "All" button upon component initialization.
- [x] Implement a handler that captures the selected category and updates the displayed questions accordingly.
- [x] Apply CSS styles to visually highlight the selected category button for clarity.

## Size

s
